# general
seed: 42
workers: 8
dataset_dir: "autodl-tmp/datasets/imagenet10/ImageNet-10"

# train options
batch_size: 16  # 200
image_size: 224
start_epoch: 0  # first train=0, eval=last epoch
epochs: 1000
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# lambda_p: 0.01  # 初始伪监督损失权重
# lambda_c: 1  # 初始一致性损失权重
lambda_s: 0.1

# model options
# resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "autodl-tmp/save/ImageNet-10"
reload: False  # first train=False

# loss options
sigma: 1 # CIFAR-100: 0.5, other: 1
# base_lr = 1e-5  # 初始学习率
learning_rate: 0.00001  # 0.0003
weight_decay: 0  # 0
instance_temperature: 0.5
cluster_temperature: 1.0


